name = "merox-erudite"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

# Pages Functions configuration
[[compatibility_flags]]
nodejs_compat = true

[env.production]
name = "merox-erudite"

[env.preview]
name = "merox-erudite-preview"